Update bootstrapcms-dast.yml

diff --git a/.github/workflows/bootstrapcms-dast.yml b/.github/workflows/bootstrapcms-dast.yml
--- a/.github/workflows/bootstrapcms-dast.yml
+++ b/.github/workflows/bootstrapcms-dast.yml
@@ -30,6 +30,14 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Check rules file existence
+        run: |
+          if [ ! -f "zap_rules/rules.conf" ]; then
+            echo "Error: rules file does not exist"
+            exit 1
+          fi
+          cat zap_rules/rules.conf
+
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
@@ -71,8 +79,9 @@ jobs:
       - name: Run ZAP baseline scan
         uses: zaproxy/action-baseline@v0.7.0
         with:
-          target: 'http://localhost:8080'  # Используйте localhost, так как приложение работает локально
+          target: 'http://5.129.250.92'
           rules_file_name: 'zap_rules/rules.conf'
+          docker_name: owasp/zap2docker-weekly
           cmd_options: '-a -j'
           fail_action: false
           allow_issue_writing: true
